version: '3.8'

services:
  samba:
    image: dperson/samba
    container_name: nas_samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./datos:/mnt/nas
    environment:
      USER: "adahi;adahi"
      SHARE: "NAS-IA;/mnt/nas;yes;no;no;adahi"
      USERID: 1000
      GROUPID: 1000
    restart: always

  ia:
    build: .
    container_name: nas_ia_brain
    volumes:
      - ./datos:/app/datos
    restart: always